language: python
python:
  - "2.7"
virtual_env:
  system_site_packages: true
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  coverage run --source=pytrustnfe setup.py nosetests
after_success:
  coveralls
